const FILTER_MAP = {
vertical_ai: { id: "ai", name: "AI", type: "vertical" },
vertical_enterpriseIt: { id: "enterprise-it", name: "Enterprise IT", type: "vertical" },
vertical_financialServices: { id: "financial-services", name: "Financial Services", type: "vertical" },
vertical_industrial: { id: "industrial", name: "Industrial", type: "vertical" },
vertical_media: { id: "media", name: "Media", type: "vertical" },
vertical_retailCpg: { id: "retail-cpg", name: "Retail / CPG", type: "vertical" },
type_analystReport: { id: "analyst-report", name: " Analyst report", type: "type" },
type_academicPublication: { id: "academic-publication", name: "Academic publication", type: "type" },
type_artificialIntelligence: { id: "artificial-intelligence", name: "Artificial intelligence", type: "type" },
type_blog: { id: "blog", name: "Blog", type: "type" },
type_byline: { id: "byline", name: "Byline", type: "type" },
type_caseStudy: { id: "case-study", name: "Case study", type: "type" },
type_coverage: { id: "coverage", name: "Coverage", type: "type" },
type_dataSheet: { id: "data-sheet", name: "Data sheet", type: "type" },
type_default: { id: "default", name: "Default", type: "type" },
type_demo: { id: "demo", name: "Demo", type: "type" },
type_ebook: { id: "ebook", name: "Ebook", type: "type" },
type_industryEvent: { id: "industry-event", name: "Industry event", type: "type" },
type_infographic: { id: "infographic", name: "Infographic", type: "type" },
type_insuranceInsight: { id: "insurance-insight", name: "Insurance insight", type: "type" },
type_itOperation: { id: "it-operation", name: "IT operation", type: "type" },
type_mediaCoverage: { id: "media-coverage", name: "Media Coverage", type: "type" },
type_partner: { id: "partner", name: "Partner", type: "type" },
type_podcast: { id: "podcast", name: "Podcast", type: "type" },
type_pressRelease: { id: "press-release", name: "Press release", type: "type" },
type_solutionVideo: { id: "solution-video", name: "Solution video", type: "type" },
type_video: { id: "video", name: "Video", type: "type" },
type_videoSeries: { id: "video-series", name: "Video series", type: "type" },
type_virtualIndustryEvent: { id: "virtual-industry-event", name: "Virtual industry event", type: "type" },
type_webinar: { id: "webinar", name: "Webinar", type: "type" },
type_whitePaper: { id: "white-paper", name: "White paper", type: "type" },
topic_cpg: { id: "cpg", name: "CPG", type: "topic" },
topic_finserveCdd: { id: "finserve-cdd", name: "FinServe CDD", type: "topic" },
topic_finserveKyc: { id: "finserve-kyc", name: "FinServe KYC", type: "topic" },
topic_finserveSanctionsScreening: { id: "finserve-sanctions-screening", name: "FinServe Sanctions Screening", type: "topic" },
topic_fsAgentic: { id: "fs-agentic", name: "FS Agentic", type: "topic" },
topic_industrialConnectedWorker: { id: "industrial-connected-worker", name: "Industrial Connected Worker", type: "topic" },
topic_industrialDataops: { id: "industrial-dataops", name: "Industrial DataOps", type: "topic" },
topic_industrialUnifiedNamespace: { id: "industrial-unified-namespace", name: "Industrial Unified Namespace", type: "topic" },
topic_mediaStreaming: { id: "media-streaming", name: "Media Streaming", type: "topic" },
topic_retailCategoryManagement: { id: "retail-category-management", name: "Retail Category Management", type: "topic" },
topic_retailContentMonetization: { id: "retail-content-monetization", name: "Retail Content Monetization", type: "topic" },
topic_retailDemandForecasting: { id: "retail-demand-forecasting", name: "Retail Demand Forecasting", type: "topic" },
topic_retailGrocery: { id: "retail-grocery", name: "Retail Grocery", type: "topic" },
topic_retailMerchandising: { id: "retail-merchandising", name: "Retail Merchandising", type: "topic" },
topic_retailStoreOperations: { id: "retail-store-operations", name: "Retail Store Operations", type: "topic" },
topic_retailSupplyChain: { id: "retail-supply-chain", name: "Retail Supply Chain", type: "topic" },
topic_verticalAi: { id: "vertical-ai", name: "Vertical AI", type: "topic" },
};

export default FILTER_MAP;
